### ISSUE TITLE
GPU configuration 

### ISSUE THREAD

**Issue by benn94** [philipperemy/yolo-9000#4]
I have checked my NVIDIA GPU configuration and the output is bellow:

```
hci2@digits-box:/yolo-9000/darknet$ echo $PATH
/usr/local/cuda-8.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/cuda-8.0/bin
```

```
hci2@digits-box:/yolo-9000/darknet$ echo $LD_LIBRARY_PATH
/usr/local/cuda-8.0/lib64

```
When I try to run 
`./darknet detector test cfg/combine9k.data cfg/yolo9000.cfg ../yolo9000-weights/yolo9000.weights data/dog.jpg`

I got this output: 
`./darknet: error while loading shared libraries: libcudart.so.7.5: cannot open shared object file: No such file or directory`

**Comment by benn94** [comment]
This is the full output:

```
hci2@digits-box:/yolo-9000$ cd darknet
hci2@digits-box:/yolo-9000/darknet$ make clean
rm -rf ./obj/gemm.o ./obj/utils.o ./obj/cuda.o ./obj/deconvolutional_layer.o ./obj/convolutional_layer.o ./obj/list.o ./obj/image.o ./obj/activations.o ./obj/im2col.o ./obj/col2im.o ./obj/blas.o ./obj/crop_layer.o ./obj/dropout_layer.o ./obj/maxpool_layer.o ./obj/softmax_layer.o ./obj/data.o ./obj/matrix.o ./obj/network.o ./obj/connected_layer.o ./obj/cost_layer.o ./obj/parser.o ./obj/option_list.o ./obj/detection_layer.o ./obj/route_layer.o ./obj/box.o ./obj/normalization_layer.o ./obj/avgpool_layer.o ./obj/layer.o ./obj/local_layer.o ./obj/shortcut_layer.o ./obj/activation_layer.o ./obj/rnn_layer.o ./obj/gru_layer.o ./obj/crnn_layer.o ./obj/demo.o ./obj/batchnorm_layer.o ./obj/region_layer.o ./obj/reorg_layer.o ./obj/tree.o libdarknet.a darknet ./obj/captcha.o ./obj/lsd.o ./obj/super.o ./obj/voxel.o ./obj/art.o ./obj/tag.o ./obj/cifar.o ./obj/go.o ./obj/rnn.o ./obj/rnn_vid.o ./obj/compare.o ./obj/segmenter.o ./obj/regressor.o ./obj/classifier.o ./obj/coco.o ./obj/dice.o ./obj/yolo.o ./obj/detector.o ./obj/writing.o ./obj/nightmare.o ./obj/swag.o ./obj/darknet.o

hci2@digits-box:/yolo-9000/darknet$ vim Makefile
hci2@digits-box:/yolo-9000/darknet$ nano Makefile
hci2@digits-box:/yolo-9000/darknet$ make
mkdir -p obj
mkdir -p backup
mkdir -p results
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/gemm.c -o obj/gemm.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/utils.c -o obj/utils.o
./src/utils.c: In function ‘fgetl’:
./src/utils.c:311:14: warning: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Wunused-result]
         fgets(&line[curr], readsize, fp);
              ^
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/cuda.c -o obj/cuda.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/deconvolutional_layer.c -o obj/deconvolutional_layer.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/convolutional_layer.c -o obj/convolutional_layer.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/list.c -o obj/list.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/image.c -o obj/image.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/activations.c -o obj/activations.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/im2col.c -o obj/im2col.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/col2im.c -o obj/col2im.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/blas.c -o obj/blas.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/crop_layer.c -o obj/crop_layer.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/dropout_layer.c -o obj/dropout_layer.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/maxpool_layer.c -o obj/maxpool_layer.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/softmax_layer.c -o obj/softmax_layer.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/data.c -o obj/data.o
./src/data.c: In function ‘load_regression_labels_paths’:
./src/data.c:448:15: warning: ignoring return value of ‘fscanf’, declared with attribute warn_unused_result [-Wunused-result]
         fscanf(file, "%f", &(y.vals[i][0]));
               ^
./src/data.c: In function ‘load_cifar10_data’:
./src/data.c:1118:14: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(bytes, 1, 3073, fp);
              ^
./src/data.c: In function ‘load_all_cifar10’:
./src/data.c:1181:18: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
             fread(bytes, 1, 3073, fp);
                  ^
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/matrix.c -o obj/matrix.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/network.c -o obj/network.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/connected_layer.c -o obj/connected_layer.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/cost_layer.c -o obj/cost_layer.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/parser.c -o obj/parser.o
./src/parser.c: In function ‘load_connected_weights’:
./src/parser.c:954:10: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(l.biases, sizeof(float), l.outputs, fp);
          ^
./src/parser.c:955:10: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(l.weights, sizeof(float), l.outputs*l.inputs, fp);
          ^
./src/parser.c:962:14: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(l.scales, sizeof(float), l.outputs, fp);
              ^
./src/parser.c:963:14: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(l.rolling_mean, sizeof(float), l.outputs, fp);
              ^
./src/parser.c:964:14: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(l.rolling_variance, sizeof(float), l.outputs, fp);
              ^
./src/parser.c: In function ‘load_batchnorm_weights’:
./src/parser.c:978:10: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(l.scales, sizeof(float), l.c, fp);
          ^
./src/parser.c:979:10: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(l.rolling_mean, sizeof(float), l.c, fp);
          ^
./src/parser.c:980:10: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(l.rolling_variance, sizeof(float), l.c, fp);
          ^
./src/parser.c: In function ‘load_convolutional_weights_binary’:
./src/parser.c:990:10: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(l.biases, sizeof(float), l.n, fp);
          ^
./src/parser.c:992:14: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(l.scales, sizeof(float), l.n, fp);
              ^
./src/parser.c:993:14: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(l.rolling_mean, sizeof(float), l.n, fp);
              ^
./src/parser.c:994:14: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(l.rolling_variance, sizeof(float), l.n, fp);
              ^
./src/parser.c:1000:14: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(&mean, sizeof(float), 1, fp);
              ^
./src/parser.c:1004:18: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
             fread(&c, sizeof(char), 1, fp);
                  ^
./src/parser.c: In function ‘load_convolutional_weights’:
./src/parser.c:1025:10: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(l.biases, sizeof(float), l.n, fp);
          ^
./src/parser.c:1027:14: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(l.scales, sizeof(float), l.n, fp);
              ^
./src/parser.c:1028:14: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(l.rolling_mean, sizeof(float), l.n, fp);
              ^
./src/parser.c:1029:14: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(l.rolling_variance, sizeof(float), l.n, fp);
              ^
./src/parser.c:1046:10: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(l.weights, sizeof(float), num, fp);
          ^
./src/parser.c: In function ‘load_weights_upto’:
./src/parser.c:1079:10: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(&major, sizeof(int), 1, fp);
          ^
./src/parser.c:1080:10: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(&minor, sizeof(int), 1, fp);
          ^
./src/parser.c:1081:10: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(&revision, sizeof(int), 1, fp);
          ^
./src/parser.c:1082:10: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(net->seen, sizeof(int), 1, fp);
          ^
./src/parser.c:1119:18: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
             fread(l.biases, sizeof(float), l.outputs, fp);
                  ^
./src/parser.c:1120:18: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
             fread(l.weights, sizeof(float), size, fp);
                  ^
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/option_list.c -o obj/option_list.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/detection_layer.c -o obj/detection_layer.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/route_layer.c -o obj/route_layer.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/box.c -o obj/box.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/normalization_layer.c -o obj/normalization_layer.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/avgpool_layer.c -o obj/avgpool_layer.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/layer.c -o obj/layer.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/local_layer.c -o obj/local_layer.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/shortcut_layer.c -o obj/shortcut_layer.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/activation_layer.c -o obj/activation_layer.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/rnn_layer.c -o obj/rnn_layer.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/gru_layer.c -o obj/gru_layer.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/crnn_layer.c -o obj/crnn_layer.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/demo.c -o obj/demo.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/batchnorm_layer.c -o obj/batchnorm_layer.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/region_layer.c -o obj/region_layer.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/reorg_layer.c -o obj/reorg_layer.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/tree.c -o obj/tree.o
nvcc  -gencode arch=compute_20,code=[sm_20,sm_21] -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN" -c ./src/convolutional_kernels.cu -o obj/convolutional_kernels.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc  -gencode arch=compute_20,code=[sm_20,sm_21] -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN" -c ./src/deconvolutional_kernels.cu -o obj/deconvolutional_kernels.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc  -gencode arch=compute_20,code=[sm_20,sm_21] -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN" -c ./src/activation_kernels.cu -o obj/activation_kernels.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc  -gencode arch=compute_20,code=[sm_20,sm_21] -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN" -c ./src/im2col_kernels.cu -o obj/im2col_kernels.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc  -gencode arch=compute_20,code=[sm_20,sm_21] -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN" -c ./src/col2im_kernels.cu -o obj/col2im_kernels.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc  -gencode arch=compute_20,code=[sm_20,sm_21] -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN" -c ./src/blas_kernels.cu -o obj/blas_kernels.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc  -gencode arch=compute_20,code=[sm_20,sm_21] -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN" -c ./src/crop_layer_kernels.cu -o obj/crop_layer_kernels.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc  -gencode arch=compute_20,code=[sm_20,sm_21] -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN" -c ./src/dropout_layer_kernels.cu -o obj/dropout_layer_kernels.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc  -gencode arch=compute_20,code=[sm_20,sm_21] -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN" -c ./src/maxpool_layer_kernels.cu -o obj/maxpool_layer_kernels.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc  -gencode arch=compute_20,code=[sm_20,sm_21] -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN" -c ./src/network_kernels.cu -o obj/network_kernels.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc  -gencode arch=compute_20,code=[sm_20,sm_21] -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  --compiler-options "-Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN" -c ./src/avgpool_layer_kernels.cu -o obj/avgpool_layer_kernels.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
ar -rv libdarknet.a obj/gemm.o obj/utils.o obj/cuda.o obj/deconvolutional_layer.o obj/convolutional_layer.o obj/list.o obj/image.o obj/activations.o obj/im2col.o obj/col2im.o obj/blas.o obj/crop_layer.o obj/dropout_layer.o obj/maxpool_layer.o obj/softmax_layer.o obj/data.o obj/matrix.o obj/network.o obj/connected_layer.o obj/cost_layer.o obj/parser.o obj/option_list.o obj/detection_layer.o obj/route_layer.o obj/box.o obj/normalization_layer.o obj/avgpool_layer.o obj/layer.o obj/local_layer.o obj/shortcut_layer.o obj/activation_layer.o obj/rnn_layer.o obj/gru_layer.o obj/crnn_layer.o obj/demo.o obj/batchnorm_layer.o obj/region_layer.o obj/reorg_layer.o obj/tree.o obj/convolutional_kernels.o obj/deconvolutional_kernels.o obj/activation_kernels.o obj/im2col_kernels.o obj/col2im_kernels.o obj/blas_kernels.o obj/crop_layer_kernels.o obj/dropout_layer_kernels.o obj/maxpool_layer_kernels.o obj/network_kernels.o obj/avgpool_layer_kernels.o 
ar: creating libdarknet.a
a - obj/gemm.o
a - obj/utils.o
a - obj/cuda.o
a - obj/deconvolutional_layer.o
a - obj/convolutional_layer.o
a - obj/list.o
a - obj/image.o
a - obj/activations.o
a - obj/im2col.o
a - obj/col2im.o
a - obj/blas.o
a - obj/crop_layer.o
a - obj/dropout_layer.o
a - obj/maxpool_layer.o
a - obj/softmax_layer.o
a - obj/data.o
a - obj/matrix.o
a - obj/network.o
a - obj/connected_layer.o
a - obj/cost_layer.o
a - obj/parser.o
a - obj/option_list.o
a - obj/detection_layer.o
a - obj/route_layer.o
a - obj/box.o
a - obj/normalization_layer.o
a - obj/avgpool_layer.o
a - obj/layer.o
a - obj/local_layer.o
a - obj/shortcut_layer.o
a - obj/activation_layer.o
a - obj/rnn_layer.o
a - obj/gru_layer.o
a - obj/crnn_layer.o
a - obj/demo.o
a - obj/batchnorm_layer.o
a - obj/region_layer.o
a - obj/reorg_layer.o
a - obj/tree.o
a - obj/convolutional_kernels.o
a - obj/deconvolutional_kernels.o
a - obj/activation_kernels.o
a - obj/im2col_kernels.o
a - obj/col2im_kernels.o
a - obj/blas_kernels.o
a - obj/crop_layer_kernels.o
a - obj/dropout_layer_kernels.o
a - obj/maxpool_layer_kernels.o
a - obj/network_kernels.o
a - obj/avgpool_layer_kernels.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./examples/captcha.c -o obj/captcha.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./examples/lsd.c -o obj/lsd.o
./examples/lsd.c: In function ‘train_dcgan’:
./examples/lsd.c:497:9: warning: unused variable ‘ay_size’ [-Wunused-variable]
     int ay_size = anet.truths*anet.batch;
         ^
./examples/lsd.c:454:11: warning: unused variable ‘orig_rate’ [-Wunused-variable]
     float orig_rate = anet.learning_rate;
           ^
./examples/lsd.c: In function ‘train_colorizer’:
./examples/lsd.c:674:9: warning: unused variable ‘ay_size’ [-Wunused-variable]
     int ay_size = anet.outputs*anet.batch;
         ^
./examples/lsd.c:672:12: warning: unused variable ‘y’ [-Wunused-variable]
     float *y = calloc(y_size, sizeof(float));
            ^
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./examples/super.c -o obj/super.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./examples/voxel.c -o obj/voxel.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./examples/art.c -o obj/art.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./examples/tag.c -o obj/tag.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./examples/cifar.c -o obj/cifar.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./examples/go.c -o obj/go.o
./examples/go.c: In function ‘engine_go’:
./examples/go.c:503:14: warning: ignoring return value of ‘scanf’, declared with attribute warn_unused_result [-Wunused-result]
         scanf("%s", buff);
              ^
./examples/go.c:521:18: warning: ignoring return value of ‘scanf’, declared with attribute warn_unused_result [-Wunused-result]
             scanf("%s", comm);
                  ^
./examples/go.c:545:18: warning: ignoring return value of ‘scanf’, declared with attribute warn_unused_result [-Wunused-result]
             scanf("%d", &boardsize);
                  ^
./examples/go.c:555:18: warning: ignoring return value of ‘scanf’, declared with attribute warn_unused_result [-Wunused-result]
             scanf("%d", &handicap);
                  ^
./examples/go.c:567:18: warning: ignoring return value of ‘scanf’, declared with attribute warn_unused_result [-Wunused-result]
             scanf("%f", &komi);
                  ^
./examples/go.c:577:22: warning: ignoring return value of ‘scanf’, declared with attribute warn_unused_result [-Wunused-result]
                 scanf("%s ", color);
                      ^
./examples/go.c:579:22: warning: ignoring return value of ‘scanf’, declared with attribute warn_unused_result [-Wunused-result]
                 scanf(" ");
                      ^
./examples/go.c:615:22: warning: ignoring return value of ‘scanf’, declared with attribute warn_unused_result [-Wunused-result]
                 scanf("%s", color);
                      ^
./examples/go.c:647:18: warning: ignoring return value of ‘scanf’, declared with attribute warn_unused_result [-Wunused-result]
             scanf("%s", type);
                  ^
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./examples/rnn.c -o obj/rnn.o
./examples/rnn.c: In function ‘train_char_rnn’:
./examples/rnn.c:137:14: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
         fread(text, 1, size, fp);
              ^
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./examples/rnn_vid.c -o obj/rnn_vid.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./src/compare.c -o obj/compare.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./examples/segmenter.c -o obj/segmenter.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./examples/regressor.c -o obj/regressor.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./examples/classifier.c -o obj/classifier.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./examples/coco.c -o obj/coco.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./examples/dice.c -o obj/dice.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./examples/yolo.c -o obj/yolo.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./examples/detector.c -o obj/detector.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./examples/writing.c -o obj/writing.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./examples/nightmare.c -o obj/nightmare.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./examples/swag.c -o obj/swag.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN -c ./examples/darknet.c -o obj/darknet.o
gcc -Iinclude/ -Isrc/ -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wall -Wfatal-errors  -Ofast -DGPU -DCUDNN obj/captcha.o obj/lsd.o obj/super.o obj/voxel.o obj/art.o obj/tag.o obj/cifar.o obj/go.o obj/rnn.o obj/rnn_vid.o obj/compare.o obj/segmenter.o obj/regressor.o obj/classifier.o obj/coco.o obj/dice.o obj/yolo.o obj/detector.o obj/writing.o obj/nightmare.o obj/swag.o obj/darknet.o libdarknet.a -o darknet -lm -pthread  -L/usr/local/cuda/lib64 -lcuda -lcudart -lcublas -lcurand -lcudnn -lstdc++  libdarknet.a
hci2@digits-box:/mnt/hdd3t/Data/hci2/borinyun/yolo-9000/darknet$ ./darknet detector test cfg/combine9k.data cfg/yolo9000.cfg ../yolo9000-weights/yolo9000.weights data/dog.jpg
./darknet: error while loading shared libraries: libcudart.so.7.5: cannot open shared object file: No such file or directory
```

**Comment by philipperemy** [comment]
Your error is:

`./darknet: error while loading shared libraries: libcudart.so.7.5: cannot open shared object file: No such file or directory`

So let's see if your file actually exists.

Try this:

```
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
```

Make sure `nvcc` is in your `$PATH` by running `nvcc`.

Check if the file is there by running:
```
ll /usr/local/cuda/lib64/libcudart.so
```

This file should be a symbolic link and points to `libcudart.so.7.5` automatically.

In my case, I have:
```
ll /usr/local/cuda/lib64/libcudart.so
lrwxrwxrwx 1 root root 16 Jun  2 12:11 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
```

Maybe you have to manually set it when you compile `darknet` with 

`cmake -DCUDA_CUDART_LIBRARY=/usr/local/cuda/lib64/libcudart.so  @[...]`

 I'm not sure exactly how it works here. Check this link if you're still blocked:

- https://stackoverflow.com/questions/19980412/how-to-let-cmake-find-cuda#comment29746097_19981506

**Comment by benn94** [comment]
Thank you for your reply.
It works now by 

```
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
```

**Comment by philipperemy** [comment]
@benn94 thanks for the feedback! Happy to hear that it worked!
